### ISSUE TITLE
Flickering of page

### ISSUE THREAD

**Issue by iftikharali** [kamleshKumarVerma/Tendy-mart-frontend#15]
I will send video via mail

I tried putting some filter and when I didn't found any result. The page is flickering while scrolling and it doesn't allow to scroll.

**Comment by kamleshKumarVerma** [comment]
@iftikharali ya it's reproducible. i am currently looking into this. will fix it very soon.

**Comment by kamleshKumarVerma** [comment]
@iftikharali  Done . fix will come in next build. closing it now.
