### ISSUE TITLE
keep the initial map zoom level to fit the path in the box

### ISSUE THREAD

**Issue by iftikharali** [kamleshKumarVerma/Tendy-mart-frontend#17]
![image](https://user-images.githubusercontent.com/4265598/35770837-2338f694-0949-11e8-8b99-4d8a190cd918.png)

**Comment by kamleshKumarVerma** [comment]
@iftikharali Here Map automatically taking the zoom level to fit the distance path in the screen.
Handling zoom level from code will be very difficult in case of draw path  . Ideally we should not control the zoom level for finding the path. Map will do it automatically.
Tried to move your current location marker and see automatically zoom level will be increased if you move marker very near to the shop.

**Comment by kamleshKumarVerma** [comment]
Invalid issue
