### ISSUE TITLE
Location share karne ka logic samajh mei nahi aya is page pe

### ISSUE THREAD

**Issue by iftikharali** [kamleshKumarVerma/Tendy-mart-frontend#22]
![image](https://user-images.githubusercontent.com/4265598/35990139-2bf6c8c2-0d29-11e8-971a-7e1341b3a964.png)

![image](https://user-images.githubusercontent.com/4265598/35990185-46884418-0d29-11e8-995c-ce499d3877f6.png)

**Comment by kamleshKumarVerma** [comment]
@iftikharali while displaying path in map, from your current location to shop location we need you current location

**Comment by kamleshKumarVerma** [comment]
@iftikharali basically this alert popup is not related to location share .. it's related to path generation from your current place to shop place in map.

and there is some issue while drawing this path .. need to check the google API. it was working earlier in temp.multishop.surge.sh . will check it and fixed it soon

**Comment by kamleshKumarVerma** [comment]
@iftikharali closing it now . done
