### ISSUE TITLE
The footer is overlapping on the action buttons 

### ISSUE THREAD

**Issue by iftikharali** [kamleshKumarVerma/Tendy-mart-frontend#23]
![image](https://user-images.githubusercontent.com/4265598/35990307-9a91392a-0d29-11e8-9362-f01973245f89.png)

**Comment by kamleshKumarVerma** [comment]
@iftikharali kitna chhota screen hai be tera :P

**Comment by kamleshKumarVerma** [comment]
fixed and it will come in next build
