### ISSUE TITLE
I can myself create review multiple time for my shop. also can abuse my own shop

### ISSUE THREAD

**Issue by iftikharali** [kamleshKumarVerma/Tendy-mart-frontend#25]
Not sure about the flag but review should not be by the same user.

![image](https://user-images.githubusercontent.com/4265598/35990730-070865b4-0d2b-11e8-9cfc-6a11b6ffc07c.png)

**Comment by iftikharali** [comment]
I can like also my own shop. (this can be not big problem but the review and flag should be protected from the same user)

**Comment by kamleshKumarVerma** [comment]
done
