### ISSUE TITLE
While editing why contact number I have to enter again. also I have to get otp again

### ISSUE THREAD

**Issue by iftikharali** [kamleshKumarVerma/Tendy-mart-frontend#27]

**Comment by kamleshKumarVerma** [comment]
For security purpose , you need to verify your contact number again. most of the sites they have this kind of feature. in our case, shop keeper's mobile number is very important for us. i want to be again verified while updating the shop for security purpose.

without mobile verification i don't want to update the shop info data.

**Comment by kamleshKumarVerma** [comment]
@iftikharali will update this as if user change the mobile number while updating shop than mobile verification is required and if user does not change the mobile number , he/she can update the shop without sending any OTP token

**Comment by kamleshKumarVerma** [comment]
done
