### ISSUE TITLE
finalize the shop categories which will available in first release

### ISSUE THREAD

**Issue by kamleshKumarVerma** [kamleshKumarVerma/Tendy-mart-frontend#29]
@iftikharali prepare one list for shop categories, which we want to be in first release.
like.
medical shop,
wine shop,
etc

**Comment by kamleshKumarVerma** [comment]
@iftikharali bhai isse dekh lena ..

**Comment by iftikharali** [comment]
As of now in my mind below list is coming
Wineshop
Medical store
Restaurant
Paying guest
Hotel
Hostel
Laundry
Hospital
Book stall
Tea stall
Refreshment stall(paan ya cigarette shop)
General store
Mobile store
Cervice Center(company wise kaise filter karega)(or ye nahi rakhna hai)

**Comment by kamleshKumarVerma** [comment]
@iftikharali Anything else ?

**Comment by kamleshKumarVerma** [comment]
@iftikharali bhai isme hostel, hotel, Paying guest sense nahi banta..
aur bhi shop categories hai jo hum sayad miss kar rahe hai.

**Comment by kamleshKumarVerma** [comment]
@iftikharali Added this much shop categories:

{ route: 'GroceyShop', displayName: 'Grocey Shop', icon: 'fa fa-object-group'},
    { route: 'MedicalShop', displayName: 'Medical Shop', icon: 'fa fa-ambulance'},
    { route: 'RestaurantsShop', displayName: 'Restaurants Shop', icon: 'fa fa-cutlery'},
    { route: 'ElectronicShop', displayName: 'Electronic Shop', icon: 'fa fa-wrench'},
    { route: 'JewelleryShop', displayName: 'Jewellery Shop', icon: 'fa fa-diamond'},
    { route: 'GeneralShop', displayName: 'General Shop', icon: 'fa fa-simplybuilt'},
    { route: 'MobileShop', displayName: 'Mobile Shop', icon: 'fa fa-mobile'},
    { route: 'WinesShop', displayName: 'Wines Shop', icon: 'fa fa-beer'},
    { route: 'RefreshmentStall', displayName: 'Refreshment Stall', icon: 'fa fa-glass'},
    { route: 'TeaStall', displayName: 'Tea Stall', icon: 'fa fa-coffee'},
    { route: 'BookStall', displayName: 'Book Stall', icon: 'fa fa-book'},
    { route: 'LaundryShop', displayName: 'Laundry Shop', icon: 'fa fa-shopping-bag'},
    { route: 'BakeryShop', displayName: 'Bakery Shop', icon: 'fa fa-birthday-cake'},
    { route: 'ChickenShop', displayName: 'Chicken Shop', icon: 'fa fa-balance-scale'},
    { route: 'WoodShop', displayName: 'Wood Shop', icon: 'fa fa-clone'},
    { route: 'MotorbikeGarageShop', displayName: 'Motorbike Garage Shop', icon: 'fa fa-motorcycle'},
    { route: 'Others', displayName: 'Others', icon: 'fa fa-globe'}


Closing it now
