### ISSUE TITLE
Need OTP improvement

### ISSUE THREAD

**Issue by kamleshKumarVerma** [kamleshKumarVerma/Tendy-mart-frontend#41]

**Comment by iftikharali** [comment]
bhai otp enter karne pe box phat ja raha hai. tujhe pata hai to thik nahi to mai screen bhejta hu

**Comment by iftikharali** [comment]
![image](https://user-images.githubusercontent.com/4265598/36271703-6998fb1a-12a5-11e8-8cef-eaafd3165630.png)

**Comment by kamleshKumarVerma** [comment]
@iftikharali bhai maine fixed kar diya hai ye issue .. bhai tu bhi apna kam jaldi jaldi kar le ... jitne bhi github issue hai tere naam pe usse khatam kar le jaldi..
coding chhor kar sare kam (image adding in all social media, email and all except coding )tere hi khate me hai .:)

**Comment by kamleshKumarVerma** [comment]
@iftikharali bhai mera development monday tak ho jayega full complete ... tubhi ak target date rakh le .. taki hum ak aur bar test karenge ak sath .. ache se before 25 feb ..

**Comment by kamleshKumarVerma** [comment]
@iftikharali done . closing it now
