### ISSUE TITLE
transparent image has issue .. loading image coming in background

### ISSUE THREAD

**Issue by kamleshKumarVerma** [kamleshKumarVerma/Tendy-mart-frontend#42]

**Comment by iftikharali** [comment]
![image](https://user-images.githubusercontent.com/4265598/36348991-70331a24-14a2-11e8-8e3d-f902db075725.png)

Still it is there

**Comment by kamleshKumarVerma** [comment]
@iftikharali yes , still it's there , will fix it soon

**Comment by kamleshKumarVerma** [comment]
@iftikharali fixed kar diya hai bhai ye wala. verify kar lena ak bar .. closing now
