### ISSUE TITLE
How to I add another shop from profile page

### ISSUE THREAD

**Issue by iftikharali** [kamleshKumarVerma/Tendy-mart-frontend#47]
![image](https://user-images.githubusercontent.com/4265598/36348999-a544abec-14a2-11e8-9105-88f9014ada8c.png)

**Comment by kamleshKumarVerma** [comment]
@iftikharali . ok i will add one button for adding shop.
Can you suggest me where should i put that button?

**Comment by kamleshKumarVerma** [comment]
done

**Comment by kamleshKumarVerma** [comment]
@iftikharali bhai ye "add shop" already header me drop-down me hai ... aur profile page me koi suitable place hi nahi hai jaha "add shop" add kiya jaye ... and also this is not major issue .. closing it now
